### ISSUE TITLE
毕设方向想做这个，不知可不可以拿来研究

### ISSUE THREAD

**Issue by Kelier** [Ovilia/Polyvia#7]
😸 自己很喜欢这个方向，但缺乏一些经验，所以想在此基础上学习

**Comment by Kelier** [comment]
npm install 报了一堆错，有影响么？我看直接有build之后的

../../nan/nan.h:495:27: note: candidate template ignored: substitution failure
      [with T = v8::Boolean]
  NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
                          ^
../../nan/nan.h:567:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:573:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:578:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:584:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:663:15: error: no type named 'WeakCallbackData' in namespace
      'v8'
    const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
          ~~~~^
../../nan/nan.h:663:31: error: expected ')'
    const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
                              ^
../../nan/nan.h:662:41: note: to match this '('
  static void _NanWeakCallbackDispatcher(
                                        ^
../../nan/nan.h:664:42: error: use of undeclared identifier 'data'
      _NanWeakCallbackInfo<T, P> *info = data.GetParameter();
                                         ^
../../nan/nan.h:755:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
13 warnings and 20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kelier/Documents/overload/Polyvia/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
npm WARN node-sass-middleware@0.3.1 requires a peer of node-sass@0.9.x but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kelier/.npm/_logs/2017-12-05T06_55_10_792Z-debug.log

**Comment by Ovilia** [comment]
看起来像是 gulp-sass 的问题，可以试试 cnpm 安装？https://github.com/cnpm/cnpm

**Comment by Kelier** [comment]
cnpm又报了新错

Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node build.js" error, exit code 1

这个移除node_modules是移除项目里的吗，我试了试貌似不行

**Comment by Ovilia** [comment]
应该是 sass npm 包的问题，你搜一下，然后下个没问题的版本

**Comment by Kelier** [comment]
okay，已经升级到最新版本
